### ISSUE TITLE
Syntax Error in TS.js in IE11

### ISSUE THREAD

**Issue by fahadash** [lord-saumagen/TypeScript-LINQ#4]
I am getting a Syntax Error in TS.js line 17 in IE11 at the following line

```ts
    class Exception {
```
Looks like it is transpiled into ES6 instead of ES5 which IE11 understands. Is there a page where I can see which browsers are supported? Do you not support IE11?

**Comment by lord-saumagen** [comment]
Dear Mr. / Mrs. fahadash,

would you please read the following paragraph of the readme.md file.

"The code compiles with the TypeScript build settings "ECMAScript version" set to "ECMAScript 6". That is in fact an alias for "ECMAScript 2015". The code passes all tests in the latest Chrome or Firefox browser."

As you can read there, the whole project is compiled to "ECMAScript 6" which is the same as "ES6".
You can of course try to compile the project with a different target setting for the typescript compiler.

Best regards, Lord Saumagen.
